### ISSUE TITLE
[Feature] svg per UUID inline aus Dateiverwaltung ausgeben lassen

### ISSUE THREAD

**Issue by akroii** [slashworks/contao-simple-svg-icons-bundle#1]
Wir benutzen in einigen Projekten sehr viele SVG-Grafiken. Diese sind alle als .svg Datei eingebunden. Kann man hierzu nicht nicht die Datei inline ausgeben lassen? 

Also: `{{svg::9723t42iu3g23i49t23-234234-234?mode=inline}}`

**Comment by sgruna** [comment]
Hallo @akroii ,

im neusten Release v1.3.0 ist die von dir beschriebene Funktionalität enthalten.
Du kannst durch die Angabe einer UUID die SVG-Datei inline ausgeben lassen. Ein zusätzlicher Parameter _mode_ ist nicht erforderlich.

**Beispiel:**
Im Dateisystem liegt eine SVG-Datei mit der UUID _a8824458-a08e-11e9-9d96-81cb79fa7a74_.
Um diese als inline SVG auszugeben, wird folgender Inserttag verwendet:
`{{svg::a8824458-a08e-11e9-9d96-81cb79fa7a74}}`

Zusätzlich können Parameter für class, id, width und height übergeben werden, um eine grundlegende Steuerung auch ohne CSS zu ermöglichen:
`{{svg::a8824458-a08e-11e9-9d96-81cb79fa7a74?class=my-class&width=200&height=50}}`

Berichte gern, ob es bei dir funktioniert.

**Comment by akroii** [comment]
Das ist ein wirklich nützliches Feature! Man könnte das auch einmal im Forum publik machen.

**Comment by akroii** [comment]
Ist ein Release für 4.7 geplant?

**Comment by sgruna** [comment]
> Ist ein Release für 4.7 geplant?

Wir verwenden momentan nur die LTS-Version, deshalb haben wir mit der 4.7 keine Erfahrung.
Da die Erweiterung ursprünglich und hauptsächlich für die interne Verwendung gedacht war, ist erstmal nichts in der Richtung geplant.
