### ISSUE TITLE
Fix your URL in CM

### ISSUE THREAD

**Issue by zonky2** [slashworks/contao-simple-svg-icons-bundle#2]
you have `https://github.com/slashworks/simple-svg-icons-bundle` saved... => 404

**Comment by zonky2** [comment]
is still broken :(

**Comment by zonky2** [comment]
halbes jahr später: ist immer noch so :(

**Comment by Stefanmelz** [comment]
Moin. Was oder wo meinst du?

**Comment by zonky2** [comment]
mach mal hier https://extensions.contao.org/?q=svg&pages=1&p=slashworks%2Fcontao-simple-svg-icons-bundle bei "Mehr" den Link zu "Quellcode" auf...

**Comment by Stefanmelz** [comment]
Done
